// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulateTurnsModels
Rcpp::List simulateTurnsModels(Rcpp::S4 ratdata, Rcpp::S4 modelData, Rcpp::S4 testModel, Rcpp::S4 turnModel, arma::vec turnStages, bool debug);
RcppExport SEXP _TurnsNew_simulateTurnsModels(SEXP ratdataSEXP, SEXP modelDataSEXP, SEXP testModelSEXP, SEXP turnModelSEXP, SEXP turnStagesSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type ratdata(ratdataSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type modelData(modelDataSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type testModel(testModelSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type turnModel(turnModelSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type turnStages(turnStagesSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(simulateTurnsModels(ratdata, modelData, testModel, turnModel, turnStages, debug));
    return rcpp_result_gen;
END_RCPP
}
// getTurnsLikelihood
std::vector<double> getTurnsLikelihood(Rcpp::S4 ratdata, Rcpp::S4 modelData, Rcpp::S4 testModel, int sim);
RcppExport SEXP _TurnsNew_getTurnsLikelihood(SEXP ratdataSEXP, SEXP modelDataSEXP, SEXP testModelSEXP, SEXP simSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type ratdata(ratdataSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type modelData(modelDataSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type testModel(testModelSEXP);
    Rcpp::traits::input_parameter< int >::type sim(simSEXP);
    rcpp_result_gen = Rcpp::wrap(getTurnsLikelihood(ratdata, modelData, testModel, sim));
    return rcpp_result_gen;
END_RCPP
}
// getProbMatrix
arma::mat getProbMatrix(Rcpp::S4 ratdata, Rcpp::S4 modelData, Rcpp::S4 testModel, int sim, bool debug);
RcppExport SEXP _TurnsNew_getProbMatrix(SEXP ratdataSEXP, SEXP modelDataSEXP, SEXP testModelSEXP, SEXP simSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type ratdata(ratdataSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type modelData(modelDataSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type testModel(testModelSEXP);
    Rcpp::traits::input_parameter< int >::type sim(simSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(getProbMatrix(ratdata, modelData, testModel, sim, debug));
    return rcpp_result_gen;
END_RCPP
}
// debugAca2Likelihood
Rcpp::List debugAca2Likelihood(Rcpp::S4 ratdata, Rcpp::S4 modelData, Rcpp::S4 testModel, int sim, bool debug);
RcppExport SEXP _TurnsNew_debugAca2Likelihood(SEXP ratdataSEXP, SEXP modelDataSEXP, SEXP testModelSEXP, SEXP simSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type ratdata(ratdataSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type modelData(modelDataSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type testModel(testModelSEXP);
    Rcpp::traits::input_parameter< int >::type sim(simSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(debugAca2Likelihood(ratdata, modelData, testModel, sim, debug));
    return rcpp_result_gen;
END_RCPP
}
// debugAca2ProbMatrix
arma::mat debugAca2ProbMatrix(Rcpp::S4 ratdata, Rcpp::S4 modelData, Rcpp::S4 testModel, int sim, bool debug);
RcppExport SEXP _TurnsNew_debugAca2ProbMatrix(SEXP ratdataSEXP, SEXP modelDataSEXP, SEXP testModelSEXP, SEXP simSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type ratdata(ratdataSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type modelData(modelDataSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type testModel(testModelSEXP);
    Rcpp::traits::input_parameter< int >::type sim(simSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(debugAca2ProbMatrix(ratdata, modelData, testModel, sim, debug));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _TurnsNew_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _TurnsNew_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _TurnsNew_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _TurnsNew_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}
// quartiles
std::vector<double> quartiles(std::vector<double> samples);
RcppExport SEXP _TurnsNew_quartiles(SEXP samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type samples(samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(quartiles(samples));
    return rcpp_result_gen;
END_RCPP
}
// simulateTurnDuration
arma::vec simulateTurnDuration(arma::mat turnTimes, arma::mat allpaths, int turnId, int turnNb, arma::vec turnStages, Rcpp::List nodeGroups, bool debug);
RcppExport SEXP _TurnsNew_simulateTurnDuration(SEXP turnTimesSEXP, SEXP allpathsSEXP, SEXP turnIdSEXP, SEXP turnNbSEXP, SEXP turnStagesSEXP, SEXP nodeGroupsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type turnTimes(turnTimesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type allpaths(allpathsSEXP);
    Rcpp::traits::input_parameter< int >::type turnId(turnIdSEXP);
    Rcpp::traits::input_parameter< int >::type turnNb(turnNbSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type turnStages(turnStagesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type nodeGroups(nodeGroupsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(simulateTurnDuration(turnTimes, allpaths, turnId, turnNb, turnStages, nodeGroups, debug));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TurnsNew_simulateTurnsModels", (DL_FUNC) &_TurnsNew_simulateTurnsModels, 6},
    {"_TurnsNew_getTurnsLikelihood", (DL_FUNC) &_TurnsNew_getTurnsLikelihood, 4},
    {"_TurnsNew_getProbMatrix", (DL_FUNC) &_TurnsNew_getProbMatrix, 5},
    {"_TurnsNew_debugAca2Likelihood", (DL_FUNC) &_TurnsNew_debugAca2Likelihood, 5},
    {"_TurnsNew_debugAca2ProbMatrix", (DL_FUNC) &_TurnsNew_debugAca2ProbMatrix, 5},
    {"_TurnsNew_rcpparma_hello_world", (DL_FUNC) &_TurnsNew_rcpparma_hello_world, 0},
    {"_TurnsNew_rcpparma_outerproduct", (DL_FUNC) &_TurnsNew_rcpparma_outerproduct, 1},
    {"_TurnsNew_rcpparma_innerproduct", (DL_FUNC) &_TurnsNew_rcpparma_innerproduct, 1},
    {"_TurnsNew_rcpparma_bothproducts", (DL_FUNC) &_TurnsNew_rcpparma_bothproducts, 1},
    {"_TurnsNew_quartiles", (DL_FUNC) &_TurnsNew_quartiles, 1},
    {"_TurnsNew_simulateTurnDuration", (DL_FUNC) &_TurnsNew_simulateTurnDuration, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_TurnsNew(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
