# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateTurnsModels <- function(ratdata, modelData, testModel, turnModel, turnStages, debug = FALSE) {
    .Call(`_TurnsNew_simulateTurnsModels`, ratdata, modelData, testModel, turnModel, turnStages, debug)
}

getTurnsLikelihood <- function(ratdata, modelData, testModel, sim) {
    .Call(`_TurnsNew_getTurnsLikelihood`, ratdata, modelData, testModel, sim)
}

getProbMatrix <- function(ratdata, modelData, testModel, sim, debug = FALSE) {
    .Call(`_TurnsNew_getProbMatrix`, ratdata, modelData, testModel, sim, debug)
}

debugAca2Likelihood <- function(ratdata, modelData, testModel, sim, debug = FALSE) {
    .Call(`_TurnsNew_debugAca2Likelihood`, ratdata, modelData, testModel, sim, debug)
}

debugAca2ProbMatrix <- function(ratdata, modelData, testModel, sim, debug) {
    .Call(`_TurnsNew_debugAca2ProbMatrix`, ratdata, modelData, testModel, sim, debug)
}

rcpparma_hello_world <- function() {
    .Call(`_TurnsNew_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_TurnsNew_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_TurnsNew_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_TurnsNew_rcpparma_bothproducts`, x)
}

quartiles <- function(samples) {
    .Call(`_TurnsNew_quartiles`, samples)
}

simulateTurnDuration <- function(turnTimes, allpaths, turnId, turnNb, turnStages, nodeGroups, debug = FALSE) {
    .Call(`_TurnsNew_simulateTurnDuration`, turnTimes, allpaths, turnId, turnNb, turnStages, nodeGroups, debug)
}

